name: Deploy to Hostinger

on:
  push:
    branches:
      - main   # change if your default branch is not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ ftp://82.197.80.243 }}
          username: ${{ u580744263.mutexly.com }}
          password: ${{ Scriptix@278 }}
          server-dir: public_html/
          local-dir: out/
